# GPT Actions Configuration for LetsCould API
# This file provides examples and templates for integrating LetsCould API with GPT Actions

# Basic Configuration
name: "LetsCould API Integration"
description: "Manage cloud infrastructure on LetsCould platform through GPT Actions"
version: "1.0.0"

# Authentication Configuration
auth:
  type: "api_key"
  header_name: "api-token"
  header_value_format: "{api_key}"
  environment_variable: "LETSCLOUD_API_TOKEN"

# API Base URLs
servers:
  - url: "https://api.letscloud.io"
    description: "Production API"
  - url: "https://api.letscloud.io"
    description: "Staging API"

# Available Actions Configuration
actions:


  # Instance Management Actions
  - name: "list_instances"
    description: "List all your instances"
    operation_id: "listInstances"
    category: "Instance Management"
    
  - name: "get_instance_details"
    description: "Get detailed information about a specific instance"
    operation_id: "getInstanceDetails"
    category: "Instance Management"
    required_params:
      - "identifier"
    
  - name: "create_instance"
    description: "Create a new instance with specified configuration"
    operation_id: "createInstance"
    category: "Instance Management"
    required_params:
      - "location_slug"
      - "plan_slug"
      - "hostname"
      - "label"
      - "image_slug"
      - "password"
    
  - name: "delete_instance"
    description: "Delete an instance from your account"
    operation_id: "deleteInstance"
    category: "Instance Management"
    required_params:
      - "identifier"
    
  - name: "power_on_instance"
    description: "Turn on a specific instance"
    operation_id: "powerOnInstance"
    category: "Instance Management"
    required_params:
      - "identifier"
    
  - name: "power_off_instance"
    description: "Turn off a specific instance"
    operation_id: "powerOffInstance"
    category: "Instance Management"
    required_params:
      - "identifier"
    
  - name: "reboot_instance"
    description: "Reboot a specific instance"
    operation_id: "rebootInstance"
    category: "Instance Management"
    required_params:
      - "identifier"
    
  - name: "reset_instance_password"
    description: "Change the root password of a specific instance"
    operation_id: "resetInstancePassword"
    category: "Instance Management"
    required_params:
      - "identifier"
      - "password"
    
  - name: "shutdown_instance"
    description: "Shutdown a running instance"
    operation_id: "shutdownInstance"
    category: "Instance Management"
    required_params:
      - "identifier"
    
  - name: "change_instance_plan"
    description: "Change the plan of an existing instance"
    operation_id: "changeInstancePlan"
    category: "Instance Management"
    required_params:
      - "identifier"
      - "plan_slug"

  # SSH Key Management Actions
  - name: "store_or_generate_ssh_key"
    description: "Store your current SSH key or generate a new one"
    operation_id: "storeOrGenerateSSHKey"
    category: "SSH Key Management"
    required_params:
      - "title"
    
  - name: "delete_ssh_key_by_slug"
    description: "Delete an SSH key from your account using its slug"
    operation_id: "deleteSSHKeyBySlug"
    category: "SSH Key Management"
    required_params:
      - "slug"

  # Snapshot Management Actions
  - name: "get_snapshot_status"
    description: "Get the current build status of a snapshot"
    operation_id: "getSnapshotStatus"
    category: "Snapshot Management"
    required_params:
      - "image_slug"
    
  - name: "update_snapshot_label"
    description: "Update the label of an existing snapshot"
    operation_id: "updateSnapshotLabel"
    category: "Snapshot Management"
    required_params:
      - "image_slug"
      - "label"
    
  - name: "delete_snapshot_by_slug"
    description: "Delete a snapshot using its slug"
    operation_id: "deleteSnapshot"
    category: "Snapshot Management"
    required_params:
      - "image_slug"
    


  # Resource Discovery Actions
  - name: "list_plans"
    description: "List all available server plans"
    operation_id: "listPlans"
    category: "Resource Discovery"
    
  - name: "list_images"
    description: "List all available OS images"
    operation_id: "listImages"
    category: "Resource Discovery"
    
  - name: "list_locations"
    description: "List all available server locations"
    operation_id: "listLocations"
    category: "Resource Discovery"
    
  - name: "list_plans_by_location"
    description: "List all available plans for a specific location"
    operation_id: "listPlansByLocation"
    category: "Resource Discovery"
    required_params:
      - "location_slug"
    
  - name: "list_images_by_location"
    description: "List all available images for a specific location"
    operation_id: "listImagesByLocation"
    category: "Resource Discovery"
    required_params:
      - "location_slug"

  # Account Information Actions
  - name: "get_profile_info"
    description: "Get your LetsCould profile information"
    operation_id: "getProfileInfo"
    category: "Account Information"

# Parameter Templates
parameter_templates:
  server_creation:
    label: "My Web Server"
    plan_slug: "basic-1gb"
    image_slug: "ubuntu-22-04"
    location_slug: "nyc1"
    hostname: "webserver-01"
    password: "SecurePassword123!"
    ssh_keys: [1, 2, 3]
  
  ssh_key_creation:
    title: "My Laptop Key"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..."
  
  snapshot_creation:
    label: "Backup before update"
    description: "Snapshot created before applying system updates"

# Usage Examples
usage_examples:
  - scenario: "Create a new web server"
    actions:
      - "list_locations"
      - "list_plans_by_location"
      - "list_images_by_location"
      - "create_instance"
    description: "First discover available resources, then create an instance"
  
  - scenario: "Manage existing instances"
    actions:
      - "list_instances"
      - "get_instance_details"
      - "power_on_instance"
      - "power_off_instance"
      - "reboot_instance"
    description: "List, view details, and control power state of instances"
  
  - scenario: "Backup and restore a server"
    actions:
      - "list_snapshots"
      - "create_snapshot"
      - "restore_snapshot"
    description: "Create a backup snapshot and restore from it if needed"
  
  - scenario: "Manage SSH access"
    actions:
      - "list_ssh_keys"
      - "create_ssh_key"
      - "delete_ssh_key"
    description: "Manage SSH keys for secure server access"
  
  - scenario: "Instance maintenance"
    actions:
      - "list_instances"
      - "reset_instance_password"
      - "change_instance_plan"
      - "shutdown_instance"
    description: "Perform maintenance tasks on instances"

# Error Handling
error_handling:
  retry_config:
    max_retries: 3
    backoff_multiplier: 2
    initial_delay: 1
  
  common_errors:
    - code: "UNAUTHORIZED"
      description: "Invalid or missing API key"
      solution: "Check your API key configuration"
    
    - code: "NOT_FOUND"
      description: "Resource not found"
      solution: "Verify the resource ID exists"
    
    - code: "VALIDATION_ERROR"
      description: "Invalid request parameters"
      solution: "Check required parameters and data types"

# Security Considerations
security:
  - "API keys should be stored securely and not exposed in logs"
  - "Use HTTPS for all API communications"
  - "Implement proper error handling to avoid exposing sensitive information"
  - "Consider implementing rate limiting on the client side"

# Best Practices
best_practices:
  - "Always validate server IDs before performing operations"
  - "Use descriptive labels for servers and snapshots"
  - "Implement proper backup strategies using snapshots"
  - "Monitor server status before performing state-changing operations"
  - "Keep SSH keys organized with meaningful titles"
