# GitHub Pages Configuration for LetsCould API GPT Actions

# Site settings
title: "LetsCould API GPT Actions"
description: "OpenAPI specification and documentation for LetsCould API integration with GPT Actions"
url: "https://letscloud-community.github.io"
baseurl: "/letscloud-openapi-gpt"

# Author information
author:
  name: "LetsCould Community"
  email: "support@letscloud.io"
  bio: "Open-source project for integrating LetsCould API with GPT Actions"
  location: "Global"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/letscloud-community/letscloud-openapi-gpt"
    
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/letscloud"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages
  - assets
  - docs

# SEO settings
seo:
  title: "LetsCould API GPT Actions"
  description: "OpenAPI specification and documentation for LetsCould API integration with GPT Actions"
  keywords: "LetsCould, API, GPT Actions, OpenAPI, cloud infrastructure, server management"
  author: "LetsCould Community"
  image: "/assets/LetsCloud_logo.png"
  type: "website"
  twitter:
    card: "summary_large_image"
    site: "@letscloud"
  facebook:
    app_id: ""
    pages: ""

# Social media
social:
  name: "LetsCould Community"
  links:
    - "https://github.com/letscloud-community/letscloud-openapi-gpt"
    
    - "https://twitter.com/letscloud"

# Analytics (optional)
google_analytics: ""
google_tag_manager: ""

# Comments (optional)
disqus:
  shortname: ""

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Timezone
timezone: "UTC"

# Encoding
encoding: "utf-8"

# Safe mode
safe: true

# Future posts
future: false

# Show drafts
show_drafts: false

# Limit posts
limit_posts: 0

# Keep files
keep_files: [".git", "assets", "docs"]

# Ignore files
ignore: [".git", "node_modules", "vendor"]

# Theme settings
theme: minima

# Minima theme settings
minima:
  social_links:
    github: letscloud-community/letscloud-openapi-gpt
    
    twitter: letscloud
  skin: auto
  dark_skin: dark
  light_skin: light
